### ISSUE TITLE
New SonarQube Plugin for Flutter

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#53]
* Add SonarQube Plugin to our application.
* Set up any metrics we need.

**Comment by Clearedkinkajou** [comment]
It is not currently possible to automate uploading the coverage report to sonarqube using CI's because an error that occurs when running in containers that is throwing error code 3. https://github.com/insideapp-oss/sonar-flutter/issues/11 I am currently in the works of developing a fix for this issue, luckily this error is not thrown when running on local machines thus we will need to upload coverage reports manually for now.

**Comment by DBatistaFerreira** [comment]
No Need for Acceptance Testing for non-user story tags :) Closing this
