### ISSUE TITLE
Google Single Sign On

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#9]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to be able to sign in to Google so that my account settings and services are synced

## ACCEPTANCE CRITERIA
* User can sign into their Google account through the application

**Comment by Clearedkinkajou** [comment]
This feature was needed to access users google calendars. Luckily a better way of retrieving calendars was developed for ticket #66. This new method allows users to retrieve any calendar that their mobile device has access to including google calendars, device calendars, and calendars in other apps. 

Due to the above mentioned reasoning this ticket is no longer needed and is now closed
